# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

#Turn on future posts
future:           true

# Setup
title:            Shahid Khaliq
tagline:		  	
description:      'I write to taste life in retrospect and to record things I might forget.'

url:              http://www.shahidkhaliq.com
baseurl:          /

author:
  name:           'Shahid Khaliq'
  url:            http://www.shahidkhaliq.com/

plugins:
  - jekyll-paginate
  - jekyll-gist

paginate:         3


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
