# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

#Turn on future posts
future:           true

# Setup
title:            Xinlei (Ray) Chen
tagline:		  	
description:      'I have always thought that I would love to live by the sea, to travel the world alone and live my life more simply.'

url:              https://raymundo1.github.io/
baseurl:          /

author:
  name:           'Xinlei (Ray) Chen'
  url:            https://raymundo1.github.io/

plugins:
  - jekyll-paginate
  - jekyll-gist

paginate:         3


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
